# -*- coding: utf-8 -*-
"""data_preprocessing_task_upwork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vjqGChsqJ6Dz5nnNEcPnDT1umZf95zvb
"""

#install the necessary libraries
import ast
import numpy as np
import pandas as pd

#loading the data
data=pd.read_csv('UpWork.csv')

data.head()

#converting the string into dictionary
data['ALARM_PAYLOAD']=data['ALARM_PAYLOAD'].apply(ast.literal_eval)

data['ALARM_PAYLOAD'][0]

#now I build columns and merge it with original data set
data_final=pd.concat([data.drop(['ALARM_PAYLOAD'], axis=1), data['ALARM_PAYLOAD'].apply(pd.Series).drop(columns=[0,1])], axis=1)

#dropping unecessary columns
data_final=data_final.drop(columns=['remaining parametes, each parameter in a column'])

data_final.head()

data_final.to_csv('final_csv.csv',index=False)

#there are duplicate columns in case we want to remove them, do this
data_update=pd.concat([data.drop(columns=['ALARM_PAYLOAD','ateTagNo'], axis=1), data['ALARM_PAYLOAD'].apply(pd.Series).drop(columns=[0,1,'messageType'])], axis=1)

data_update=data_update.drop(columns=['remaining parametes, each parameter in a column'])

data_update.to_csv('final_update_csv.csv',index=False)

